### ISSUE TITLE
Question about config param in location handler

### ISSUE THREAD

**Issue by nela** [yioneko/nvim-vtsls#13]
The config parameter is passed to the location handler, used for source definitions and file references. The handler checks whether loclist or on_list is set to use on multiple location items.

```lua
if config.loclist then
    vim.fn.setloclist(0, {}, " ", { title = title, items = items, context = ctx })
    vim.api.nvim_command("lopen")
elseif config.on_list then
    config.on_list({ title = title, items = items, context = ctx })
```

Where and how can I set these config properties, so that they are used by this handler (rather than writing another handler)? 
I've tried setting `vim.lsp.buf.references` as written about in the [docs](https://neovim.io/doc/user/lsp.html#lsp-buf). And also tried overriding the `workspace/executeCommand` handler, yet no success.

**Comment by yioneko** [comment]
For now there is no way to pass the `config` argument to the default handler. The code is originally copied from nvim builtin lsp handler since it is private. However, there is a relatively simple way to override the handler without fully rewriting yours:
```lua
local loc_handler =  require("vtsls.config").get().handlers.source_definition
local handler_with_config = function(err, locations, ctx)
  local config = {}
  return loca_handler(err, locations, ctx, config)
end
require("vtsls").config({ handlers = { source_definition = handler_with_config } })
```

**Comment by yioneko** [comment]
Also read if you are interested: https://github.com/neovim/neovim/issues/11533

**Comment by nela** [comment]
Alright, thanks for the reply!
