### ISSUE TITLE
Is it possible to autocomplete tsconfig with vtsls and nvim

### ISSUE THREAD

**Issue by Demianeen** [yioneko/nvim-vtsls#3]
From what I see in tsconfig, I think that vtsls can give error in tsconfig. For instance, I do get:
 │     Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'es2022', 'esnext', 'node16', 'nodenext'. ts [24, 15]

Is it possible to set up vtsls an nvim to autocomplete json. Or is it currently unsupported?

**Comment by yioneko** [comment]
Yes, vtsls (also tsserver) doesn't have support for json completion while there is validation support for tsconfig. Use [`vscode-json-language-server`](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#jsonls) instead for completion.

**Comment by Demianeen** [comment]
Thanks! Now it is working)
