### ISSUE TITLE
Is it possible to get all workspace diagnostics like in vscode?

### ISSUE THREAD

**Issue by Demianeen** [yioneko/nvim-vtsls#7]
Hi! I only recently discovered the power of nvim-vtsls with its powerful code actions. This is awesome!

While doing this I remembered how vscode had a view of all workspace errors/analysis. Is it possible to get it in nvim?

**Comment by yioneko** [comment]
See option [`typescript.tsserver.experimental.enableProjectDiagnostics`](https://github.com/yioneko/vtsls/blob/41ad8c9d3f9dbd122ce3259564f34d020b7d71d9/packages/service/configuration.schema.json#L911-L915)

**Comment by Demianeen** [comment]
That did the trick! Thanks)
