### ISSUE TITLE
gql tada completion

### ISSUE THREAD

**Issue by omelette-watin** [yioneko/nvim-vtsls#8]
as a LazyVim user i migrated from tsserver to this package instead and all feels smoother so thanks a lot for this.

I've just noticed that i don't get autocompletions from [gql.tada](https://gql-tada.0no.co/) which i used to have with tsserver. 
Any idea on what could cause that ?

Thanks a lot for your work

**Comment by yioneko** [comment]
See [troubleshooting](https://github.com/yioneko/vtsls#typescript-plugin-not-activated). Try to set `vtsls.autoUseWorkspaceTsdk = true`.

**Comment by omelette-watin** [comment]
Thanks !
